apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: nextcloud

resources:
  - namespace.yaml
  - persistentvolume.yaml
  - persistentvolumeclaim.yaml
  - configmap-hooks.yaml
  - mariadb.yaml
  - nextcloud.yaml
  - service.yaml
