---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-sso
  namespace: jellyfin
  labels:
    app: jellyfin-oauth2-proxy
    app.kubernetes.io/name: jellyfin-oauth2-proxy
    app.kubernetes.io/component: auth-proxy
spec:
  type: ClusterIP
  selector:
    app: jellyfin-oauth2-proxy
  ports:
    - name: http
      port: 80
      targetPort: 4180
      protocol: TCP
