apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: vmstation-jellyfin-production

resources:
  - ../../base

labels:
  - includeSelectors: false
    pairs:
      environment: production

patches:
  - target:
      kind: ConfigMap
      name: jellyfin-config
      namespace: jellyfin
    patch: |-
      - op: replace
        path: /data/JELLYFIN_PublishedServerUrl
        value: "http://192.168.4.61:30096"
      - op: replace
        path: /data/JELLYFIN_LOG_LEVEL
        value: "Warning"

  - target:
      kind: Deployment
      name: jellyfin
      namespace: jellyfin
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          kubernetes.io/hostname: storagenodet3500
      - op: replace
        path: /spec/template/spec/volumes/2
        value:
          name: jellyfin-media
          hostPath:
            path: /mnt/media
            type: Directory

  - target:
      kind: Service
      name: jellyfin-service
      namespace: jellyfin
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 30096
      - op: add
        path: /spec/ports/1/nodePort
        value: 30920

  - target:
      kind: Deployment
      name: jellyfin-oauth2-proxy
      namespace: jellyfin
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          kubernetes.io/hostname: storagenodet3500

  - target:
      kind: Deployment
      name: jellyfin-oauth2-proxy
      namespace: jellyfin
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: jellyfin-oauth2-proxy
        namespace: jellyfin
      spec:
        template:
          spec:
            containers:
              - name: oauth2-proxy
                env:
                  - name: OAUTH2_PROXY_REDIRECT_URL
                    value: "http://192.168.4.61:30097/oauth2/callback"
                  - name: OAUTH2_PROXY_OIDC_ISSUER_URL
                    value: ""
                  - name: OAUTH2_PROXY_LOGIN_URL
                    value: "http://192.168.4.63:30180/auth/realms/cluster-services/protocol/openid-connect/auth"
                  - name: OAUTH2_PROXY_REDEEM_URL
                    value: "http://keycloak-http.identity.svc.cluster.local:80/auth/realms/cluster-services/protocol/openid-connect/token"
                  - name: OAUTH2_PROXY_PROFILE_URL
                    value: "http://keycloak-http.identity.svc.cluster.local:80/auth/realms/cluster-services/protocol/openid-connect/userinfo"
                  - name: OAUTH2_PROXY_VALIDATE_URL
                    value: "http://keycloak-http.identity.svc.cluster.local:80/auth/realms/cluster-services/protocol/openid-connect/userinfo"
                  - name: OAUTH2_PROXY_OIDC_JWKS_URL
                    value: "http://keycloak-http.identity.svc.cluster.local:80/auth/realms/cluster-services/protocol/openid-connect/certs"

  - target:
      kind: Service
      name: jellyfin-sso
      namespace: jellyfin
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/externalTrafficPolicy
        value: Local
      - op: add
        path: /spec/ports/0/nodePort
        value: 30097

images:
  - name: jellyfin/jellyfin
    newTag: "10.9.11"
